apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-project-deployment
  labels:
    app: console-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-project
  template:
    metadata:
      labels:
        app: console-project
    spec:
      containers:
        - name: console-project
          image: ghcr.io/${IMAGE_NAME}:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
